name: deivao_drawer
description: Deivao Custom Drawer.
version: 1.0.0
author: David Araujo
homepage: 

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
