name: deivao_drawer
description: Deivao Beautiful Custom Drawer with easy implementation and customization.
version: 1.0.0+5
author: David Araujo - Flutterando <davidsdearaujo@gmail.com>
homepage: https://github.com/davidsdearaujo
github: https://github.com/davidsdearaujo/deivao_drawer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
